ReRe.Ui/Controllers/CommentaireModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReRe.Data.DbContext;
using ReRe.Data.Models;

namespace ReRe.Ui.Controllers
{
    public class CommentaireModelsController : BaseController
    {
        private readonly ReReDbContext _context;

        public CommentaireModelsController(ReReDbContext context)
        {
            _context = context;
        }

        // GET: CommentaireModels
        public async Task<IActionResult> Index(string search, string sort)
        {
            var userId = HttpContext.Session.GetInt32("Id");
            var commentaires = _context.Commentaires
                .Include(c => c.UserModel)
                .Include(c => c.RessourceModel)
                .Include(c => c.CommentaireParent)
                .Where(c => c.UserId == userId)
                .AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                commentaires = commentaires.Where(c =>
                    c.Comment.Contains(search) ||
                    c.UserModel.Nom.Contains(search) ||
                    c.UserModel.Prenom.Contains(search) ||
                    c.RessourceModel.Categorie.Contains(search)
                );
            }

            switch (sort)
            {
                case "auteur":
                    commentaires = commentaires.OrderBy(c => c.UserModel.Nom);
                    break;
                case "ressource":
                    commentaires = commentaires.OrderBy(c => c.RessourceModel.Categorie);
                    break;
                default:
                    commentaires = commentaires.OrderByDescending(c => c.Date);
                    break;
            }

            ViewBag.SearchQuery = search;
            ViewBag.SortOrder = sort;

            return View(await commentaires.ToListAsync());
        }


        // GET: CommentaireModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentaireModel = await _context.Commentaires
                .Include(c => c.CommentaireParent)
                .Include(c => c.RessourceModel)
                .Include(c => c.UserModel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commentaireModel == null)
            {
                return NotFound();
            }

            return View(commentaireModel);
        }

        // GET: CommentaireModels/Create
        public IActionResult Create(int ressourceId, int? commentaireId = null)
        {
            ViewData["RessourceId"] = ressourceId;
            ViewData["CommentaireId"] = commentaireId;
            ViewData["UserId"] = new SelectList(_context.Utilisateurs, "Id", "Nom");
            return View();
        }


        // POST: CommentaireModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Comment,RessourceId,CommentaireId,Date")] CommentaireModel commentaireModel)
        {
            if (ModelState.IsValid)
            {
                commentaireModel.Date = DateTime.Now;
                _context.Add(commentaireModel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "RessourceModels", new { id = commentaireModel.RessourceId });
            }
            ViewData["CommentaireId"] = new SelectList(_context.Commentaires, "Id", "Id", commentaireModel.CommentaireId);
            ViewData["RessourceId"] = new SelectList(_context.Ressources, "Id", "Categorie", commentaireModel.RessourceId);
            ViewData["UserId"] = new SelectList(_context.Utilisateurs, "Id", "Nom", commentaireModel.UserId);
            return View(commentaireModel);
        }

        // GET: CommentaireModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentaireModel = await _context.Commentaires.FindAsync(id);
            if (commentaireModel == null)
            {
                return NotFound();
            }
            ViewData["CommentaireId"] = new SelectList(_context.Commentaires, "Id", "Id", commentaireModel.CommentaireId);
            ViewData["RessourceId"] = new SelectList(_context.Ressources, "Id", "Categorie", commentaireModel.RessourceId);
            ViewData["UserId"] = new SelectList(_context.Utilisateurs, "Id", "Nom", commentaireModel.UserId);
            return View(commentaireModel);
        }

        // POST: CommentaireModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Comment,RessourceId,CommentaireId,Date")] CommentaireModel commentaireModel)
        {
            if (id != commentaireModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(commentaireModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentaireModelExists(commentaireModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CommentaireId"] = new SelectList(_context.Commentaires, "Id", "Id", commentaireModel.CommentaireId);
            ViewData["RessourceId"] = new SelectList(_context.Ressources, "Id", "Categorie", commentaireModel.RessourceId);
            ViewData["UserId"] = new SelectList(_context.Utilisateurs, "Id", "Nom", commentaireModel.UserId);
            return View(commentaireModel);
        }

        // GET: CommentaireModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commentaireModel = await _context.Commentaires
                .Include(c => c.CommentaireParent)
                .Include(c => c.RessourceModel)
                .Include(c => c.UserModel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commentaireModel == null)
            {
                return NotFound();
            }

            return View(commentaireModel);
        }

        // POST: CommentaireModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commentaireModel = await _context.Commentaires.FindAsync(id);
            if (commentaireModel != null)
            {
                _context.Commentaires.Remove(commentaireModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentaireModelExists(int id)
        {
            return _context.Commentaires.Any(e => e.Id == id);
        }
    }
}

ReRe.Ui/Controllers/RessourceModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReRe.Data.DbContext;
using ReRe.Data.Models;
using System.Linq;

namespace ReRe.Ui.Controllers
{
    public class RessourceModelsController : BaseController
    {
        private readonly ReReDbContext _context;

        public RessourceModelsController(ReReDbContext context)
        {
            _context = context;
        }

        // GET: RessourceModels
        public async Task<IActionResult> Index(string search, string sort, RessourceModel r)
        {
            // Récupération des infos utilisateur
            ViewBag.Email = HttpContext.Session.GetString("UserEmail");
            ViewBag.Nom = HttpContext.Session.GetString("UserName");
            ViewBag.Prenom = HttpContext.Session.GetString("UserFirstName");
            ViewBag.Id = HttpContext.Session.GetInt32("Id");
            ViewBag.RoleId = HttpContext.Session.GetInt32("RoleId");

            // Préparation de la requête
            var ressources = _context.Ressources.AsQueryable();

            // Filtrage
            if (!string.IsNullOrWhiteSpace(search))
            {
                ressources = ressources.Where(r =>
                    r.Name.Contains(search) ||
                    r.Description.Contains(search) ||
                    r.Type.Libelle.Contains(search) ||
                    r.Categorie.Contains(search));
            }

            // Tri
            switch (sort)
            {
                case "categorie":
                    ressources = ressources.OrderBy(r => r.Categorie);
                    break;
                case "type":
                    ressources = ressources.OrderBy(r => r.Type);
                    break;
                case "date":
                    ressources = ressources.OrderByDescending(r => r.CreationDate);
                    break;
                case "nom":
                default:
                    ressources = ressources.OrderBy(r => r.Name);
                    break;
            }

            ViewBag.SearchQuery = search;
            ViewBag.SortOrder = sort;

            return View(await ressources.ToListAsync());
        }


        // GET: RessourceModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var ressourceModel = await _context.Ressources
                .Include(r => r.Commentaires)
                .ThenInclude(c => c.UserModel)
                .Include(r => r.Utilisateurs)   // <-- Ajout ici
                .FirstOrDefaultAsync(m => m.Id == id);


            if (ressourceModel == null)
                return NotFound();

            // Charger tous les commentaires de la ressource
            var commentaires = await _context.Commentaires
                .Where(c => c.RessourceId == id)
                .Include(c => c.UserModel)
                .ToListAsync();

            // Construire la hiérarchie en mémoire
            foreach (var commentaire in commentaires)
            {
                commentaire.CommentairesEnfants = commentaires
                    .Where(c => c.CommentaireId == commentaire.Id)
                    .ToList();
            }

            // N’afficher que les racines
            ressourceModel.Commentaires = commentaires
                .Where(c => c.CommentaireId == null)
                .ToList();
            // Liste des utilisateurs pour ajout
            ViewBag.AllUsers = await _context.Users.ToListAsync();

            return View(ressourceModel);
        }



        private async Task<List<SelectListItem>> GetTypeSelectListAsync()
        {
            return await _context.TypeModel
                .Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Libelle
                })
                .ToListAsync();
        }

        // GET: RessourceModels/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Types = await GetTypeSelectListAsync();
            return View();
        }

        // POST: RessourceModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Categorie,TypeId")] RessourceModel ressourceModel)
        {
            if (ModelState.IsValid)
            {
                ressourceModel.Creator = ViewBag.Nom;
                ressourceModel.CreationDate = DateTime.Now;
                _context.Add(ressourceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Types = await GetTypeSelectListAsync();
            return View(ressourceModel);
        }

        // GET: RessourceModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var ressourceModel = await _context.Ressources.FindAsync(id);
            if (ressourceModel == null) return NotFound();

            ViewBag.Types = await GetTypeSelectListAsync();
            return View(ressourceModel);
        }

        // POST: RessourceModels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Categorie,TypeId,CreationDate")] RessourceModel ressourceModel)
        {
            if (id != ressourceModel.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ressourceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RessourceModelExists(ressourceModel.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Types = await GetTypeSelectListAsync();
            return View(ressourceModel);
        }


        // GET: RessourceModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ressourceModel = await _context.Ressources
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ressourceModel == null)
            {
                return NotFound();
            }

            return View(ressourceModel);
        }

        // POST: RessourceModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ressourceModel = await _context.Ressources.FindAsync(id);
            if (ressourceModel != null)
            {
                _context.Ressources.Remove(ressourceModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RessourceModelExists(int id)
        {
            return _context.Ressources.Any(e => e.Id == id);
        }

        [HttpPost]
        public async Task<IActionResult> AssignUsers(int ressourceId, List<int> userIds)
        {
            var ressource = await _context.Ressources
                .Include(r => r.Utilisateurs)
                .FirstOrDefaultAsync(r => r.Id == ressourceId);

            if (ressource == null)
                return NotFound();

            var selectedUsers = await _context.Utilisateurs.Where(u => userIds.Contains(u.Id)).ToListAsync();

            ressource.Utilisateurs.Clear();
            foreach (var user in selectedUsers)
            {
                ressource.Utilisateurs.Add(user);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = ressourceId });
        }

    }
}

ReRe.Ui/Views/RessourceModels/Create.cshtml
@model ReRe.Data.Models.RessourceModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RessourceModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Categorie" class="control-label"></label>
                <input asp-for="Categorie" class="form-control" />
                <span asp-validation-for="Categorie" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" asp-items="ViewBag.Types" class="form-select"></select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ReRe.Ui/Views/RessourceModels/Delete.cshtml
@model ReRe.Data.Models.RessourceModel

@{
    ViewData["Title"] = "Suppression de ressource";
}

<div class="container">
    <h1 class="mb-4 text-danger">Supprimer la ressource</h1>

    <div class="alert alert-warning">
        <h4 class="alert-heading">Es-tu sûr de vouloir supprimer cette ressource ?</h4>
        <p>Cette action est irréversible.</p>
    </div>

    <div class="card mb-4">
        <div class="card-body">
            <dl class="row mb-0">
                <dt class="col-sm-3">Nom</dt>
                <dd class="col-sm-9">@Model.Name</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">@Model.Description</dd>

                <dt class="col-sm-3">Catégorie</dt>
                <dd class="col-sm-9">@Model.Categorie</dd>

                <dt class="col-sm-3">Type</dt>
                <dd class="col-sm-9">@Model.Type</dd>

                <dt class="col-sm-3">Date de création</dt>
                <dd class="col-sm-9">@Model.CreationDate.ToString("dd/MM/yyyy")</dd>
            </dl>
        </div>
    </div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger me-2">
            <i class="bi bi-trash me-1"></i> Supprimer
        </button>
        <a asp-action="Index" class="btn btn-secondary">Annuler</a>
    </form>
</div>

ReRe.Ui/Views/RessourceModels/Details.cshtml
@model ReRe.Data.Models.RessourceModel

@{
    ViewData["Title"] = "Détails";
}

<div class="container mt-4">
    <h1 class="mb-4">@ViewData["Title"]</h1>

    <div class="card shadow-sm">
        <div class="card-body">
            <h4 class="card-title mb-3">Informations sur la ressource</h4>
            <dl class="row">
                <dt class="col-sm-3 text-muted">@Html.DisplayNameFor(model => model.Name)</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>

                <dt class="col-sm-3 text-muted">@Html.DisplayNameFor(model => model.Description)</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Description)</dd>

                <dt class="col-sm-3 text-muted">@Html.DisplayNameFor(model => model.Categorie)</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Categorie)</dd>

                <dt class="col-sm-3 text-muted">@Html.DisplayNameFor(model => model.Type)</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Type)</dd>

                <dt class="col-sm-3 text-muted">@Html.DisplayNameFor(model => model.CreationDate)</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.CreationDate)</dd>
            </dl>
        </div>
    </div>
    <div class="mt-5">
        <h3>Commentaires</h3>
        @await Html.PartialAsync("_Commentaires", Model.Commentaires?.Where(c => c.CommentaireId == null).ToList())
    </div>
    @if (ViewBag.RoleId > 0)
    {
        <a class="btn btn-outline-primary mt-3"
           asp-controller="CommentaireModels"
           asp-action="Create"
           asp-route-ressourceId="@Model.Id">
            Ajouter un commentaire
        </a>
    }
    <div class="mt-4 d-flex gap-3">
        @if (ViewBag.Nom == @Model.Creator || ViewBag.RoleId > 2)
        {
            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Modifier</a>
        }
        <a class="btn btn-secondary" asp-action="Index">Retour à la liste</a>
    </div>
</div>

ReRe.Ui/Views/RessourceModels/Edit.cshtml
@model ReRe.Data.Models.RessourceModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="mb-4">Modifier la ressource</h1>

<div class="row">
    <div class="col-md-6 col-lg-5">
        <form asp-action="Edit" novalidate>
            <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Categorie" class="form-label"></label>
                <input asp-for="Categorie" class="form-control" />
                <span asp-validation-for="Categorie" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="TypeId" class="form-label"></label>
                <select asp-for="TypeId" asp-items="ViewBag.Types" class="form-select"></select>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="CreationDate" class="form-label"></label>
                <input asp-for="CreationDate" type="date" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Enregistrer</button>
            <a asp-action="Index" class="btn btn-secondary ms-2">Retour à la liste</a>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ReRe.Ui/Views/RessourceModels/Index.cshtml
@model IEnumerable<ReRe.Data.Models.RessourceModel>

@{
    ViewData["Title"] = "Liste des ressources";
}

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">Ressources</h1>
    @if (ViewBag.RoleId > 0)
    {
        <a asp-action="Create" class="btn btn-success d-flex align-items-center gap-1">
            <i class="bi bi-plus-circle"></i> Nouvelle ressource
        </a>
    }
</div>

<form method="get" class="row g-3 align-items-end mb-4">
    <div class="col-md-4">
        <label for="search" class="form-label">Recherche</label>
        <input type="text" class="form-control" id="search" name="search" value="@ViewBag.SearchQuery" placeholder="Nom, description, type, etc.">
    </div>
    <div class="col-md-4">
        <label for="sort" class="form-label">Trier par</label>
        <select class="form-select" id="sort" name="sort">
            <option value="nom" selected="@(ViewBag.SortOrder == "nom")">Nom</option>
            <option value="categorie" selected="@(ViewBag.SortOrder == "categorie")">Catégorie</option>
            <option value="type" selected="@(ViewBag.SortOrder == "type")">Type</option>
            <option value="date" selected="@(ViewBag.SortOrder == "date")">Date de création</option>
        </select>
    </div>
    <div class="col-md-4">
        <button type="submit" class="btn btn-primary w-100">
            <i class="bi bi-search"></i> Rechercher
        </button>
    </div>
</form>

<div class="row g-4">
    @foreach (var item in Model)
    {
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">@item.Name</h5>

                    <div class="mb-2">
                        <span class="badge bg-info text-dark me-1">@item.Categorie</span>
                        <span class="badge bg-secondary">@item.Type?.Libelle</span>
                    </div>

                    <p class="card-text text-truncate" style="flex-grow: 1; max-height: 4.5em; overflow: hidden;">
                        @item.Description
                    </p>

                    <small class="text-muted mb-3">@item.CreationDate.ToString("dd/MM/yyyy")</small>

                    <div class="mt-auto d-flex justify-content-end gap-2">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary" title="Détails">
                            <i class="bi bi-eye"></i>
                        </a>
                        @if (ViewBag.Nom == item.Creator || ViewBag.RoleId > 2)
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-warning" title="Modifier">
                                <i class="bi bi-pencil"></i>
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger" title="Supprimer">
                                <i class="bi bi-trash"></i>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ReRe.Ui/Views/RessourceModels/_Commentaires.cshtml
@model List<ReRe.Data.Models.CommentaireModel>

@if (Model != null && Model.Any())
{
    <div class="list-unstyled">
        @foreach (var commentaire in Model)
        {
            var isEditing = ViewBag.EditCommentId != null && ViewBag.EditCommentId == commentaire.Id;

            <div class="card mb-3 border-start border-3 shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <strong class="text-primary">@commentaire.UserModel?.Prenom @commentaire.UserModel?.Nom</strong>
                        <small class="text-muted">@commentaire.Date.ToString("g")</small>
                    </div>

                    @if (isEditing)
                    {
                        <form asp-action="Edit" asp-controller="CommentaireModels" method="post">
                            <input type="hidden" name="Id" value="@commentaire.Id" />
                            <input type="hidden" name="RessourceId" value="@commentaire.RessourceId" />
                            <div class="mb-2">
                                <textarea name="Comment" class="form-control" rows="3">@commentaire.Comment</textarea>
                            </div>
                            <div class="d-flex justify-content-end gap-2">
                                <button type="submit" class="btn btn-sm btn-primary">Enregistrer</button>
                                <a href="@Url.Action("Details", "Ressources", new { id = commentaire.RessourceId })" class="btn btn-sm btn-secondary">Annuler</a>
                            </div>
                        </form>
                    }
                    else
                    {
                        <p class="card-text">@commentaire.Comment</p>
                        <div class="d-flex gap-2">
                            @if (ViewBag.RoleId > 0)
                            {
                                <a class="btn btn-sm btn-outline-secondary"
                                   asp-controller="CommentaireModels"
                                   asp-action="Create"
                                   asp-route-ressourceId="@commentaire.RessourceId"
                                   asp-route-commentaireId="@commentaire.Id">
                                    Répondre
                                </a>
                            }
                            @if ((ViewBag.UserId == commentaire.UserModel?.Id) || ViewBag.RoleId > 2)
                            {
                                <a class="btn btn-sm btn-outline-warning"
                                   href="@Url.Action("Edit", "CommentaireModels", new { id = commentaire.Id })">
                                    Modifier
                                </a>
                            }
                        </div>
                    }

                    @* Affichage récursif des réponses *@
                    @if (commentaire.CommentairesEnfants != null && commentaire.CommentairesEnfants.Any())
                    {
                        <div class="mt-3 ps-4">
                            @await Html.PartialAsync("_Commentaires", commentaire.CommentairesEnfants.ToList())
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}
else
{
    <p class="text-muted">Aucun commentaire pour le moment.</p>
}